### ISSUE TITLE
Create new key - structlog.KeyAutoTime with automatically updating time

### ISSUE THREAD

**Issue by MarcSky** [powerman/structlog#7]
Hello everyone!

I have little problem using this logger lib when I need to get real time operation.
When I setup logger with params
```
SetDefaultKeyvals(
    structlog.KeyTime, time.Now().Format(time.StampMicro),
)
```
I get same times and I need call my own wrapper
```
func GetLogger() *structlog.Logger {
	return structlog.New(
		structlog.KeyTime, time.Now().Format(time.StampMicro),
	)
}
```
For getting actually time. Its not a very comfortably to use, its will be better if existed same functionality from box.
I can make a fork and add this in function SetDefaultKeyvals but I think its will be cosy for all users.
Thank you.

**Comment by powerman** [comment]
Well, the current design reasoning for including time in output is:
- this library is designed for use in services, because for command-line tools stdlib's "log" is good enough
- services are usually runs under some sort of supervision, either as docker container or using runit/s6/etc.
- all these supervisors usually adds current time to service stdout/stderr output (docker does it by default, runit/s6 usually send service output to logger sub-service like svlogd which is able to add time to log lines)
- so, only case when time is actually useful in service output is when it output JSON for sending logs to ELK/etc.

That's why current implementation include current time only when output JSON.

What is your use case and why do you need it to output time in plain text format?

**Comment by MarcSky** [comment]
> What is your use case and why do you need it to output time in plain text format?

I using output time in plain text because its most easy way to show time of operation (error), I don't use "log" because I try to use one way of logging and besides output time I using different settings structlog (number code line in output, and etc).

Any dockers/supervisours require especial knowledge how to cooking this and, for example, not every my teammate can do this :)

Plus, I like when code have one style and simplicity.
It's just simple feature but very useful I think.

**Comment by powerman** [comment]
Sounds fair. :smile: Actually I often found myself in similar position - I get used to structlog and sometimes just wanna see time of operation while `go run` debugging or while running some command-line tools which share code with a service and that code already uses structlog.

I'll see what I can do. Thanks for raising an issue.

**Comment by powerman** [comment]
Please try 0.7.1, is should do what you want this way:
```go
structlog.New(structlog.KeyTime, structlog.Auto).SetTimeFormat(time.StampMicro)
```

**Comment by MarcSky** [comment]
@powerman thanks a lot for your work!
